name: Build

on:
  push:
    branches:
    - 'master'
    - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: actions/checkout@v2
      - run: node common/scripts/install-run-rush.js change --verify
        name: 'Verify Change Logs'
      - run: node common/scripts/install-run-rush.js install
        name: 'Rush Install'
      - run: node common/scripts/install-run-rush.js rebuild
        name: 'Rush Rebuild'
      - run: node common/scripts/install-run-rush.js test
        name: 'Rush Test'

