name: Build

on:
  push:
    branches: [master, develop]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: actions/checkout@v2
      - script: 'node common/scripts/install-run-rush.js change --verify'
        displayName: 'Verify Change Logs'
      - script: 'node common/scripts/install-run-rush.js install'
        displayName: 'Rush Install'
      - script: 'node common/scripts/install-run-rush.js rebuild --verbose --production'
        displayName: 'Rush Rebuild'
      - script: 'node common/scripts/install-run-rush.js test'
        displayName: 'Rush Test'

