name: Build

on:
  push:
    branches: [develop]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run test:all
      - run: npm run build core
      - run: npm run build reduxify
      - run: npm run build qapp-qapp-core
      - run: npm run build qapp-qapp-react
      
