name: Publish

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - script: 'node common/scripts/install-run-rush.js version --bump --target-branch ${GITHUB_REF##*/}'
        displayName: 'Rush Version'
      - script: 'node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch ${GITHUB_REF##*/} --add-commit-details --set-access-level public'
        displayName: 'Rush Publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      
